[Details]
Name = "timesplit"
ID = "timesplit"
Version = "0.0.1"
Build = 6

[LinuxAndBSD]
GenericName = "TimeSplit"
Categories = ["Time managment"]
Comment = "Divide your time into pre planed sections"
Keywords = ["orginization","time","management"]

[Migrations]
fyneDo = true
